// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoi5Qic_qixNGEk5ZukIAA5RVi0IR-Sh8',
    appId: '1:484516782994:android:3bd6a18a786547353b174b',
    messagingSenderId: '484516782994',
    projectId: 'venus-b35eb',
    storageBucket: 'venus-b35eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDBYTWZYL2y_s8XZEjeoWmXln820Ky9U0',
    appId: '1:484516782994:ios:e3cd69a1b614a41b3b174b',
    messagingSenderId: '484516782994',
    projectId: 'venus-b35eb',
    storageBucket: 'venus-b35eb.appspot.com',
    androidClientId: '484516782994-ib7u2uovenurlkpcnqno68q7p4bfg79d.apps.googleusercontent.com',
    iosClientId: '484516782994-q88235ui24uenj150tuog8nmur20bol2.apps.googleusercontent.com',
    iosBundleId: 'willalex.venusdating.app',
  );
}
