// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRMLhPTaY5z20TdaCJoMemeEUovOgxzYk',
    appId: '1:947732727022:android:2e831bbd111b423dfe5fff',
    messagingSenderId: '947732727022',
    projectId: 'venus-99940',
    storageBucket: 'venus-99940.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp9gIepcTlH-dV-de_4frbO37RYKtpL7Y',
    appId: '1:947732727022:ios:01bd62915c362ec9fe5fff',
    messagingSenderId: '947732727022',
    projectId: 'venus-99940',
    storageBucket: 'venus-99940.appspot.com',
    androidClientId: '947732727022-jjim06aovhtrs05a9fnk5ck8cqoqfs8b.apps.googleusercontent.com',
    iosClientId: '947732727022-t6l622aqup67nmsph9ei81vlna5590nn.apps.googleusercontent.com',
    iosBundleId: 'com.example.venus',
  );
}
